######################################################################
# Automatically generated by qmake (2.01a) ?r. lis 25 17:43:14 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += phonon sql

# Input
HEADERS += hrwplayer.h
FORMS += hrwplayer.ui
SOURCES += hrwplayer.cpp main.cpp
